# Generated by Django 2.1 on 2018-12-17 14:35

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('middle_name', models.CharField(default='', max_length=100, null=True)),
                ('full_name', models.CharField(default='', max_length=200, null=True)),
                ('national_identifier', models.IntegerField(default='', null=True)),
                ('job_positions', models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('manager', 'Manager'), ('developer', 'Developer')], max_length=100)),
                ('age', models.IntegerField(default='', null=True)),
                ('Date Of Birth', models.DateField(auto_now_add=True)),
                ('place_of_birth', models.CharField(default='', max_length=100, null=True)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('nationality', models.CharField(default='', max_length=100, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('military_status', models.CharField(choices=[('ex', 'Exempted'), ('co', 'Completed'), ('re', 'In Resume')], max_length=2)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user', models.Model),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
