# Generated by Django 2.1 on 2018-12-18 08:00

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=100, null=True)),
                ('last_name', models.CharField(default='', max_length=100, null=True)),
                ('middle_name', models.CharField(default='', max_length=100, null=True)),
                ('full_name', models.CharField(default='', max_length=200, null=True)),
                ('national_identifier', models.IntegerField(default='', null=True)),
                ('job_positions', models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('manager', 'Manager'), ('developer', 'Developer')], max_length=100)),
                ('age', models.IntegerField(default='', null=True)),
                ('Date Of Birth', models.DateField(auto_now_add=True)),
                ('place_of_birth', models.CharField(default='', max_length=100, null=True)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('nationality', models.CharField(default='', max_length=100, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('military_status', models.CharField(choices=[('ex', 'Exempted'), ('co', 'Completed'), ('re', 'In Resume')], max_length=2)),
            ],
        ),
    ]
